extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9978
      http:
        endpoint: 0.0.0.0:9979

  # Collect metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 120s
          static_configs:
            - targets:
              - "balance-reader:8080"
              - "transaction-history:8080"
              - "ledger-writer:8080"
          metrics_path: "/z/prometheus"

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  logging:
    logLevel: debug

  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]
