apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
spec:
  selector:
    matchLabels:
      app: contacts
  template:
    metadata:
      labels:
        app: contacts
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: contacts
          image: ghcr.io/nginxinc/bos-contacts:v1.1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: publickey
              mountPath: /root/.ssh
              readOnly: true
          env:
            - name: STATSD_HOST
              value: statsd-prometheus-statsd-exporter.prometheus.svc.cluster.local:9125
            - name: STATSD_PREFIX
              value: bos.contacts
            - name: VERSION
              value: v1.2.0
            - name: PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: ENABLE_TRACING
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: ENABLE_TRACING
            - name: ENABLE_METRICS
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: ENABLE_METRICS
                  # Valid levels are debug, info, warning, error, critical.
                  # If no valid level is set, will default to info.
            - name: LOG_LEVEL
              value: info
            - name: APP_NAME
              value: contacts
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: accounts-db-config
          readinessProbe:
            httpGet:
              path: /z/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /z/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
      volumes:
        - name: publickey
          secret:
            secretName: jwt-key
            items:
              - key: jwtRS256.key.pub
                path: publickey
---
apiVersion: v1
kind: Service
metadata:
  name: contacts
spec:
  type: ClusterIP
  selector:
    app: contacts
  ports:
    - name: http
      port: 8080
      targetPort: 8080
