apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: front
          image: ghcr.io/nginxinc/bos-frontend:v1.1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: publickey
              mountPath: /root/.ssh
              readOnly: true
          env:
            - name: VERSION
              value: v1.2.0
            - name: PORT
              value: "8080"
            - name: STATSD_HOST
              value: statsd-prometheus-statsd-exporter.prometheus.svc.cluster.local:9125
            - name: STATSD_PREFIX
              value: bos.frontend
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: ENABLE_TRACING
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: ENABLE_TRACING
            - name: ENABLE_METRICS
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: ENABLE_METRICS
            - name: SCHEME
              value: http
              # Valid levels are debug, info, warning, error, critical. If no valid level is set, defaults to info.
            - name: LOG_LEVEL
              value: info
              # Set to "true" to enable the CymbalBank logo + title
              # - name: CYMBAL_LOGO
              #   value: "false"
              # Customize the bank name used in the header. Defaults to 'Bank of Anthos' - when CYMBAL_LOGO is true, uses 'CymbalBank'
            - name: BANK_NAME
              value: Bank of Sirius
            - name: DEFAULT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: demo-data-config
                  key: DEMO_LOGIN_USERNAME
            - name: DEFAULT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: demo-data-config
                  key: DEMO_LOGIN_PASSWORD
            - name: APP_NAME
              value: frontend
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: service-api-config
          readinessProbe:
            httpGet:
              path: /z/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /z/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 30
      volumes:
        - name: publickey
          secret:
            secretName: jwt-key
            items:
              - key: jwtRS256.key.pub
                path: publickey
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
