kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ledger-db
spec:
  serviceName: ledger-db
  replicas: 1
  selector:
    matchLabels:
      app: ledger-db
  template:
    metadata:
      labels:
        app: ledger-db
    spec:
      serviceAccountName: default
      containers:
        - name: postgres
          image: ghcr.io/nginxinc/bos-ledger-db:v1.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: ENABLE_TRACING
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: ENABLE_TRACING
            - name: ENABLE_METRICS
              valueFrom:
                configMapKeyRef:
                  name: tracing-config
                  key: ENABLE_METRICS
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: ledger-db-config
            - configMapRef:
                name: demo-data-config
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgresdb
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db
spec:
  type: ClusterIP
  selector:
    app: ledger-db
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
